### ISSUE TITLE
Error while trying to connect OBS

### ISSUE THREAD

**Issue by piotrva** [brunnolou/streaming-room#25]
Windows 10
Installed Node.js, ffmpeg.
When trying to start stream following error displays:

> _stream_readable.js:642
>   throw new ERR_METHOD_NOT_IMPLEMENTED('_read()');
>   ^
> 
> Error [ERR_METHOD_NOT_IMPLEMENTED]: The _read() method is not implemented
>     at BufferPool.Readable._read (_stream_readable.js:642:9)
>     at BufferPool.Readable.read (_stream_readable.js:481:10)
>     at BufferPool.read (H:\Streaming\streaming-room-master\node_modules\rtmp-server\buffer-pool.js:27:18)
>     at parseRtmpMessage (H:\Streaming\streaming-room-master\node_modules\rtmp-server\client.js:830:22)
>     at parseRtmpMessage.next (<anonymous>)
>     at BufferPool.push (H:\Streaming\streaming-room-master\node_modules\rtmp-server\buffer-pool.js:21:17)
>     at Socket.<anonymous> (H:\Streaming\streaming-room-master\node_modules\rtmp-server\server.js:20:43)
>     at Socket.emit (events.js:315:20)
>     at addChunk (_stream_readable.js:309:12)
>     at readableAddChunk (_stream_readable.js:284:9) {
>   code: 'ERR_METHOD_NOT_IMPLEMENTED'
> }

**Comment by jericopulvera** [comment]
Same thing happened to me but then I downgraded the node version to v12.21.0 and it works.

**Comment by ekofi** [comment]
Any updates? @piotrva

**Comment by piotrva** [comment]
@ekofi Finally other persons at my facility did the streaming so I was not revisiting it.
