### ISSUE TITLE
Error when trying to start streaming via OBS

### ISSUE THREAD

**Issue by Faynot** [brunnolou/streaming-room#36]
D:\penix\streaming-room\node_modules\rtmp-server\client.js:848
    message.formatType = chunkBasicHeader[0] >> 6;
                                         ^

TypeError: Cannot read properties of null (reading '0')
    at parseRtmpMessage (D:\penix\streaming-room\node_modules\rtmp-server\client.js:848:42)
    at parseRtmpMessage.next (<anonymous>)
    at BufferPool.push (D:\penix\streaming-room\node_modules\rtmp-server\buffer-pool.js:21:17)
    at Socket.<anonymous> (D:\penix\streaming-room\node_modules\rtmp-server\server.js:20:43)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v20.12.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mohankr123** [comment]
I have also encounter same issue with obs
